### ISSUE TITLE
example .config/sab/config.yml ?

### ISSUE THREAD

**Issue by sanderjo** [andrewstuart/dlite#2]
Starting dlite, I get

```
sander@flappie:~/git/dlite$ go build
sander@flappie:~/git/dlite$ ./dlite 
2016/02/24 17:04:23 Error opening config confFile:
    open /home/sander/.config/sab/config.yml: no such file or directory
```

I tried this:

```
sander@flappie:~/git/dlite$ touch /home/sander/.config/sab/config.yml
sander@flappie:~/git/dlite$ 
sander@flappie:~/git/dlite$ ./dlite 
2016/02/24 17:05:45 No server configured. Please provide a valid usenet server name.
```

Hmmm ... Is there an instruction how to fill this config file?

**Comment by andrewstuart** [comment]
Yeah, that could probably be a better experience. Unfortunately, I've not done anything with this project in a while, and last I remember I was still having some issues with it.

One caveat is that I only ever set it up to use the NZBGeek API, so if you have their service it should work for you, but otherwise probably won't. Any NNTP (usenet) provider should work, though.

I've uploaded an example config file [here](https://github.com/andrewstuart/dlite/blob/master/examples/config.yaml) if you're using NZBGeek and would like to give it a try.
